### ISSUE TITLE
Active probing resistance

### ISSUE THREAD

**Issue by nametoolong** [SPIN-UMass/MassBrowser#96]
The server part, the relay part, and all those under threat of blocking need active probing resistance, or the GFW or something might succeed in attacking MassBrowser using an active probing like the way they blocked Tor.

**Comment by srxzr** [comment]
We will use domain fronting for the server so it shouldn't be a problem. 

For the relays, the way  Massbrowser works is different from Tor. Every client needs a session created by the server to be able to connect to the relay.

**Comment by nametoolong** [comment]
Thanks for clarifying this.
